### ISSUE TITLE
Error occured if status code of github is 404

### ISSUE THREAD

**Issue by rochefort** [rochefort/cocoapods-search#2]
```sh
$ pod-search chart
Searching .................../Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mechanize-2.7.3/lib/mechanize/http/agent.rb:308:in `fetch': 404 => Net::HTTPNotFound for https://github.com/jnic/JNLineChart -- unhandled response (Mechanize::ResponseCodeError)
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/mechanize-2.7.3/lib/mechanize.rb:440:in `get'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:56:in `scrape_social_score'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:35:in `block (2 levels) in get_pods'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:32:in `each'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:32:in `block in get_pods'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:28:in `each'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:28:in `get_pods'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/executor.rb:19:in `search'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/command.rb:22:in `search'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/lib/cocoapods/search/command.rb:42:in `method_missing'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/trsw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/cocoapods-search-0.0.6/bin/pod-search:5:in `<top (required)>'
	from /Users/trsw/.rbenv/versions/2.2.0/bin/pod-search:23:in `load'
	from /Users/trsw/.rbenv/versions/2.2.0/bin/pod-search:23:in `<main>'
```

**Comment by rochefort** [comment]
Fix: #3
